export const states = [
      {
        Abbreviation:"AL",
        State:"Alabama"
      },
      {
        Abbreviation:"AK",
        State:"Alaska"
      },
      {
        Abbreviation:"AZ",
        State:"Arizona"
      },
      {
        Abbreviation:"AR",
        State:"Arkansas"
      },
      {
        Abbreviation:"CA",
        State:"California"
      },
      {
        Abbreviation:"CO",
        State:"Colorado"
      },
      {
        Abbreviation:"CT",
        State:"Connecticut"
      },
      {
        Abbreviation:"DE",
        State:"Delaware"
      },
      {
        Abbreviation:"DC",
        State:"District Of Columbia"
      },
      {
        Abbreviation:"FL",
        State:"Florida"
      },
      {
        Abbreviation:"GA",
        State:"Georgia"
      },
      {
        Abbreviation:"HI",
        State:"Hawaii"
      },
      {
        Abbreviation:"ID",
        State:"Idaho"
      },
      {
        Abbreviation:"IL",
        State:"Illinois"
      },
      {
        Abbreviation:"IN",
        State:"Indiana"
      },
      {
        Abbreviation:"IA",
        State:"Iowa"
      },
      {
        Abbreviation:"KS",
        State:"Kansas"
      },
      {
        Abbreviation:"KY",
        State:"Kentucky"
      },
      {
        Abbreviation:"LA",
        State:"Louisiana"
      },
      {
        Abbreviation:"ME",
        State:"Maine"
      },
      {
        Abbreviation:"MD",
        State:"Maryland"
      },
      {
        Abbreviation:"MA",
        State:"Massachusetts"
      },
      {
        Abbreviation:"MI",
        State:"Michigan"
      },
      {
        Abbreviation:"MN",
        State:"Minnesota"
      },{
        Abbreviation:"MS",
        State:"Mississippi"
      },{
        Abbreviation:"MO",
        State:"Missouri"
      },{
        Abbreviation:"MT",
        State:"Montana"
      },{
        Abbreviation:"NE",
        State:"Nebraska"
      },{
        Abbreviation:"NV",
        State:"Nevada"
      },{
        Abbreviation:"NH",
        State:"New Hampshire"
      },{
        Abbreviation:"NJ",
        State:"New Jersey"
      },{
        Abbreviation:"NM",
        State:"New Mexico"
      },{
        Abbreviation:"NY",
        State:"New York"
      },{
        Abbreviation:"NC",
        State:"North Carolina"
      },{
        Abbreviation:"ND",
        State:"North Dakota"
      },{
        Abbreviation:"OH",
        State:"Ohio"
      },{
        Abbreviation:"OK",
        State:"Oklahoma"
      },{
        Abbreviation:"OR",
        State:"Oregon"
      },{
        Abbreviation:"PA",
        State:"Pennsylvania"
      },{
        Abbreviation:"RI",
        State:"Rhode Island"
      },{
        Abbreviation:"SC",
        State:"South Carolina"
      },{
        Abbreviation:"SD",
        State:"South Dakota"
      },{
        Abbreviation:"TN",
        State:"Tennessee"
      },{
        Abbreviation:"TX",
        State:"Texas"
      },{
        Abbreviation:"UT",
        State:"Utah"
      },{
        Abbreviation:"VT",
        State:"Vermont"
      },{
        Abbreviation:"VA",
        State:"Virginia"
      },{
        Abbreviation:"WA",
        State:"Washington"
      },{
        Abbreviation:"WV",
        State:"West Virginia"
      },{
        Abbreviation:"WI",
        State:"Wisconsin"
      },
      {
        Abbreviation:"WY",
        State:"Wyoming"
      }
    ];